{"name": "To Check the functionality of Accept_Page With Valid & Invalid Data.", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=netTimeout&u=https%3A//www.google.com/&c=UTF-8&d=The%20server%20at%20www.google.com%20is%20taking%20too%20long%20to%20respond.\nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:488:5\ncheckReadyState@chrome://remote/content/marionette/navigate.js:64:24\nonNavigation@chrome://remote/content/marionette/navigate.js:312:39\nemit@resource://gre/modules/EventEmitter.jsm:160:20\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.jsm:42:25\n\n", "trace": "  File \"C:\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Feature\\steps\\StepDefination.py\", line 163, in step_impl\n    context.driver2.get(\"https://www.google.com/\")\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given User Friend open Browser, Enter Url, Navigate To Log_in Page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=netTimeout&u=https%3A//www.google.com/&c=UTF-8&d=The%20server%20at%20www.google.com%20is%20taking%20too%20long%20to%20respond.\nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:181:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:488:5\ncheckReadyState@chrome://remote/content/marionette/navigate.js:64:24\nonNavigation@chrome://remote/content/marionette/navigate.js:312:39\nemit@resource://gre/modules/EventEmitter.jsm:160:20\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.jsm:42:25\n\n", "trace": "  File \"C:\\Python39\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Python39\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"Feature\\steps\\StepDefination.py\", line 163, in step_impl\n    context.driver2.get(\"https://www.google.com/\")\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 430, in get\n    self.execute(Command.GET, {'url': url})\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 418, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 243, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1634795051026, "stop": 1634795140755}, {"name": "When User Friend Enter Username With Invalid Data", "status": "skipped", "start": 1634795140757, "stop": 1634795140757}, {"name": "And User Friend Click On start Button", "status": "skipped", "start": 1634795140757, "stop": 1634795140757}, {"name": "And User Friend Validate onesignal pop-up functionality With click on Later Button", "status": "skipped", "start": 1634795140757, "stop": 1634795140757}, {"name": "And User Friend Enter Username With Valid Data", "status": "skipped", "start": 1634795140757, "stop": 1634795140757}, {"name": "And User Friend Click on Start Buttons", "status": "skipped", "start": 1634795140757, "stop": 1634795140757}, {"name": "Then User Friend Should be Navigate to Answer Page  Successfully", "status": "skipped", "start": 1634795140757, "stop": 1634795140757}], "start": 1634795051024, "stop": 1634795140757, "uuid": "311f8afc-4e63-4cd9-9154-994b92731c72", "historyId": "03c917ac6824ab0c8e6cc20d4dd5291a", "fullName": "Wowdare User Side End to End Functionality: To Check the functionality of Accept_Page With Valid & Invalid Data.", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "Accept_Page"}, {"name": "feature", "value": "Wowdare User Side End to End Functionality"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}